# Base image
FROM ubuntu:22.04

# Set environment variables
ENV DISPLAY 0
ENV QT_X11_NO_MITSHM 1
ENV DEBIAN_FRONTEND=noninteractive

# set image name
LABEL Name=ros2_humble

# 포트 노출
EXPOSE 10000:10000

# Update package list and install necessary packages
RUN apt-get update && \
    apt-get install -y \
    software-properties-common \
    curl \
    git \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Add ROS repository and install ROS packages
RUN apt-get update && \
    apt-get install -y software-properties-common curl gnupg && \
    add-apt-repository universe && \
    apt-get update

# Add ROS2 repository
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" |tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Install ROS2 Humble and related packages
RUN apt-get update && \
    apt-get install -y ros-humble-desktop ros-dev-tools ros-humble-xacro ros-humble-joint-state-publisher ros-humble-joint-state-publisher-gui && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set up ROS environment
RUN echo 'source /opt/ros/humble/setup.bash' >> /root/.bashrc

# Define working directory
WORKDIR /root/workspace

# 필요한 패키지 설치
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt

# Set script permission
# RUN chmod +x /workspace/start_ros2.sh

# Entry point
# CMD ["/bin/bash", "-c", "/workspace/start_ros2.sh"]
